# fly.toml app configuration file generated for motticon on 2023-12-29T20:52:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "motticon"
primary_region = "ams"

[env]
  VITE_API_URL="https://motticon-backend.fly.dev/"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.http_options.response.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
