# fly.toml app configuration file generated for motticon-prod on 2024-03-17T22:59:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'motticon-prod'
primary_region = 'arn'

[build]

[env]
  VITE_API_URL = 'https://motticon-backend-prod.fly.dev/'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
    [http_service.http_options.response]
      [http_service.http_options.response.headers]
        Access-Control-Allow-Headers = '*'
        Access-Control-Allow-Methods = '*'
        Access-Control-Allow-Origin = '*'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
