services:
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    build: 
      context: db/
    ports:
      - "5432:5432"

  backend:
    depends_on:
      - db
    build: 
      context: backend/
      dockerfile: Dockerfile.dev
    env_file:
      - backend/.env     
    ports:
      - "4000:4000"
    volumes:
      - "./backend:/app"

  frontend:
    depends_on:
      - backend
    build: 
      context: frontend/
      dockerfile: Dockerfile.dev
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    