# fly.toml app configuration file generated for motticon-backend-prod on 2024-03-17T21:44:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'motticon-backend-prod'
primary_region = 'arn'

[build]

[env]
  FRONTEND_URL = 'https://motticon-prod.fly.dev'

[[mounts]]
  source = 'motticon_photos'
  destination = '/photos'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_options]
    [http_service.http_options.response]
      [http_service.http_options.response.headers]
        Access-Control-Allow-Headers = '*'
        Access-Control-Allow-Methods = '*'
        Access-Control-Allow-Origin = '*'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
